# Generated by Django on 2026-02-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="selected_size",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="selected_color",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]

